//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 06:39:36 AM CEST 
//


package com.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDate;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for Plan_Cena complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Plan_Cena">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cena" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Pocetak_Vazenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Kraj_Vazenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plan_Cena", propOrder = {
    "cena",
    "pocetakVazenja",
    "krajVazenja"
})
@Entity(name = "PlanCena")
@Table(name = "PLAN_CENA")
@Inheritance(strategy = InheritanceType.JOINED)
public class PlanCena
    implements Serializable, Equals, HashCode
{

    @XmlElement(name = "Cena")
    protected double cena;
    @XmlElement(name = "Pocetak_Vazenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pocetakVazenja;
    @XmlElement(name = "Kraj_Vazenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar krajVazenja;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the cena property.
     * 
     */
    @Basic
    @Column(name = "CENA", precision = 20, scale = 10)
    public double getCena() {
        return cena;
    }

    /**
     * Sets the value of the cena property.
     * 
     */
    public void setCena(double value) {
        this.cena = value;
    }

    /**
     * Gets the value of the pocetakVazenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getPocetakVazenja() {
        return pocetakVazenja;
    }

    /**
     * Sets the value of the pocetakVazenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPocetakVazenja(XMLGregorianCalendar value) {
        this.pocetakVazenja = value;
    }

    /**
     * Gets the value of the krajVazenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getKrajVazenja() {
        return krajVazenja;
    }

    /**
     * Sets the value of the krajVazenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKrajVazenja(XMLGregorianCalendar value) {
        this.krajVazenja = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @Basic
    @Column(name = "POCETAK_VAZENJA_ITEM")
    @Temporal(TemporalType.DATE)
    public Date getPocetakVazenjaItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDate.class, this.getPocetakVazenja());
    }

    public void setPocetakVazenjaItem(Date target) {
        setPocetakVazenja(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDate.class, target));
    }

    @Basic
    @Column(name = "KRAJ_VAZENJA_ITEM")
    @Temporal(TemporalType.DATE)
    public Date getKrajVazenjaItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDate.class, this.getKrajVazenja());
    }

    public void setKrajVazenjaItem(Date target) {
        setKrajVazenja(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDate.class, target));
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof PlanCena)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final PlanCena that = ((PlanCena) object);
        {
            double lhsCena;
            lhsCena = this.getCena();
            double rhsCena;
            rhsCena = that.getCena();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cena", lhsCena), LocatorUtils.property(thatLocator, "cena", rhsCena), lhsCena, rhsCena)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsPocetakVazenja;
            lhsPocetakVazenja = this.getPocetakVazenja();
            XMLGregorianCalendar rhsPocetakVazenja;
            rhsPocetakVazenja = that.getPocetakVazenja();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "pocetakVazenja", lhsPocetakVazenja), LocatorUtils.property(thatLocator, "pocetakVazenja", rhsPocetakVazenja), lhsPocetakVazenja, rhsPocetakVazenja)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsKrajVazenja;
            lhsKrajVazenja = this.getKrajVazenja();
            XMLGregorianCalendar rhsKrajVazenja;
            rhsKrajVazenja = that.getKrajVazenja();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "krajVazenja", lhsKrajVazenja), LocatorUtils.property(thatLocator, "krajVazenja", rhsKrajVazenja), lhsKrajVazenja, rhsKrajVazenja)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            double theCena;
            theCena = this.getCena();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cena", theCena), currentHashCode, theCena);
        }
        {
            XMLGregorianCalendar thePocetakVazenja;
            thePocetakVazenja = this.getPocetakVazenja();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "pocetakVazenja", thePocetakVazenja), currentHashCode, thePocetakVazenja);
        }
        {
            XMLGregorianCalendar theKrajVazenja;
            theKrajVazenja = this.getKrajVazenja();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "krajVazenja", theKrajVazenja), currentHashCode, theKrajVazenja);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
