//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 08:04:01 PM CEST 
//


package com.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id_jedinice" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}User"/>
 *         &lt;element name="Lokacija" type="{}Lokacija_Tip"/>
 *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Opis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Broj_Osoba" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}Kategorija_Smestaja"/>
 *         &lt;element ref="{}Tip_Smestaja"/>
 *         &lt;sequence>
 *           &lt;element name="Picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}Dodatne_Usluge"/>
 *         &lt;/sequence>
 *         &lt;element name="Plan_Cena">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Cena" type="{}Plan_Cena_Tip" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idJedinice",
    "user",
    "lokacija",
    "naziv",
    "opis",
    "brojOsoba",
    "kategorijaSmestaja",
    "tipSmestaja",
    "picture",
    "dodatneUsluge",
    "planCena"
})
@XmlRootElement(name = "Smestajna_Jedinica")
public class SmestajnaJedinica {

    @XmlElement(name = "Id_jedinice")
    protected int idJedinice;
    @XmlElement(name = "User", required = true)
    protected User user;
    @XmlElement(name = "Lokacija", required = true)
    protected LokacijaTip lokacija;
    @XmlElement(name = "Naziv", required = true)
    protected String naziv;
    @XmlElement(name = "Opis", required = true)
    protected String opis;
    @XmlElement(name = "Broj_Osoba")
    protected int brojOsoba;
    @XmlElement(name = "Kategorija_Smestaja", required = true)
    protected KategorijaSmestaja kategorijaSmestaja;
    @XmlElement(name = "Tip_Smestaja", required = true)
    protected TipSmestaja tipSmestaja;
    @XmlElement(name = "Picture", required = true)
    protected List<byte[]> picture;
    @XmlElement(name = "Dodatne_Usluge", required = true)
    protected DodatneUsluge dodatneUsluge;
    @XmlElement(name = "Plan_Cena", required = true)
    protected SmestajnaJedinica.PlanCena planCena;

    /**
     * Gets the value of the idJedinice property.
     * 
     */
    public int getIdJedinice() {
        return idJedinice;
    }

    /**
     * Sets the value of the idJedinice property.
     * 
     */
    public void setIdJedinice(int value) {
        this.idJedinice = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the lokacija property.
     * 
     * @return
     *     possible object is
     *     {@link LokacijaTip }
     *     
     */
    public LokacijaTip getLokacija() {
        return lokacija;
    }

    /**
     * Sets the value of the lokacija property.
     * 
     * @param value
     *     allowed object is
     *     {@link LokacijaTip }
     *     
     */
    public void setLokacija(LokacijaTip value) {
        this.lokacija = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the opis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpis(String value) {
        this.opis = value;
    }

    /**
     * Gets the value of the brojOsoba property.
     * 
     */
    public int getBrojOsoba() {
        return brojOsoba;
    }

    /**
     * Sets the value of the brojOsoba property.
     * 
     */
    public void setBrojOsoba(int value) {
        this.brojOsoba = value;
    }

    /**
     * Gets the value of the kategorijaSmestaja property.
     * 
     * @return
     *     possible object is
     *     {@link KategorijaSmestaja }
     *     
     */
    public KategorijaSmestaja getKategorijaSmestaja() {
        return kategorijaSmestaja;
    }

    /**
     * Sets the value of the kategorijaSmestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link KategorijaSmestaja }
     *     
     */
    public void setKategorijaSmestaja(KategorijaSmestaja value) {
        this.kategorijaSmestaja = value;
    }

    /**
     * Gets the value of the tipSmestaja property.
     * 
     * @return
     *     possible object is
     *     {@link TipSmestaja }
     *     
     */
    public TipSmestaja getTipSmestaja() {
        return tipSmestaja;
    }

    /**
     * Sets the value of the tipSmestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipSmestaja }
     *     
     */
    public void setTipSmestaja(TipSmestaja value) {
        this.tipSmestaja = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the picture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPicture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * byte[]
     * 
     */
    public List<byte[]> getPicture() {
        if (picture == null) {
            picture = new ArrayList<byte[]>();
        }
        return this.picture;
    }

    /**
     * Gets the value of the dodatneUsluge property.
     * 
     * @return
     *     possible object is
     *     {@link DodatneUsluge }
     *     
     */
    public DodatneUsluge getDodatneUsluge() {
        return dodatneUsluge;
    }

    /**
     * Sets the value of the dodatneUsluge property.
     * 
     * @param value
     *     allowed object is
     *     {@link DodatneUsluge }
     *     
     */
    public void setDodatneUsluge(DodatneUsluge value) {
        this.dodatneUsluge = value;
    }

    /**
     * Gets the value of the planCena property.
     * 
     * @return
     *     possible object is
     *     {@link SmestajnaJedinica.PlanCena }
     *     
     */
    public SmestajnaJedinica.PlanCena getPlanCena() {
        return planCena;
    }

    /**
     * Sets the value of the planCena property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmestajnaJedinica.PlanCena }
     *     
     */
    public void setPlanCena(SmestajnaJedinica.PlanCena value) {
        this.planCena = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Cena" type="{}Plan_Cena_Tip" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cena"
    })
    public static class PlanCena {

        @XmlElement(name = "Cena", required = true)
        protected List<PlanCenaTip> cena;

        /**
         * Gets the value of the cena property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cena property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCena().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlanCenaTip }
         * 
         * 
         */
        public List<PlanCenaTip> getCena() {
            if (cena == null) {
                cena = new ArrayList<PlanCenaTip>();
            }
            return this.cena;
        }

    }

}
