//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 08:04:17 PM CEST 
//


package com.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id_Tipa" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Naziv_Tipa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Opis_Tipa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idTipa",
    "nazivTipa",
    "opisTipa"
})
@XmlRootElement(name = "Tip_Smestaja")
public class TipSmestaja {

    @XmlElement(name = "Id_Tipa")
    protected int idTipa;
    @XmlElement(name = "Naziv_Tipa", required = true)
    protected String nazivTipa;
    @XmlElement(name = "Opis_Tipa", required = true)
    protected String opisTipa;

    /**
     * Gets the value of the idTipa property.
     * 
     */
    public int getIdTipa() {
        return idTipa;
    }

    /**
     * Sets the value of the idTipa property.
     * 
     */
    public void setIdTipa(int value) {
        this.idTipa = value;
    }

    /**
     * Gets the value of the nazivTipa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivTipa() {
        return nazivTipa;
    }

    /**
     * Sets the value of the nazivTipa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivTipa(String value) {
        this.nazivTipa = value;
    }

    /**
     * Gets the value of the opisTipa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpisTipa() {
        return opisTipa;
    }

    /**
     * Sets the value of the opisTipa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisTipa(String value) {
        this.opisTipa = value;
    }

}
