//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.01 at 05:25:45 PM CEST 
//


package com.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for Dodatna_Usluga complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dodatna_Usluga">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naziv_Usluge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Opis_Usluge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dodatna_Usluga", propOrder = {
    "nazivUsluge",
    "opisUsluge"
})
@Entity(name = "DodatnaUsluga")
@Table(name = "DODATNA_USLUGA")
@Inheritance(strategy = InheritanceType.JOINED)
public class DodatnaUsluga
    implements Serializable, Equals, HashCode
{

    @XmlElement(name = "Naziv_Usluge", required = true)
    protected String nazivUsluge;
    @XmlElement(name = "Opis_Usluge", required = true)
    protected String opisUsluge;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the nazivUsluge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NAZIV_USLUGE", length = 255)
    public String getNazivUsluge() {
        return nazivUsluge;
    }

    /**
     * Sets the value of the nazivUsluge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivUsluge(String value) {
        this.nazivUsluge = value;
    }

    /**
     * Gets the value of the opisUsluge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "OPIS_USLUGE", length = 255)
    public String getOpisUsluge() {
        return opisUsluge;
    }

    /**
     * Sets the value of the opisUsluge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisUsluge(String value) {
        this.opisUsluge = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof DodatnaUsluga)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final DodatnaUsluga that = ((DodatnaUsluga) object);
        {
            String lhsNazivUsluge;
            lhsNazivUsluge = this.getNazivUsluge();
            String rhsNazivUsluge;
            rhsNazivUsluge = that.getNazivUsluge();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nazivUsluge", lhsNazivUsluge), LocatorUtils.property(thatLocator, "nazivUsluge", rhsNazivUsluge), lhsNazivUsluge, rhsNazivUsluge)) {
                return false;
            }
        }
        {
            String lhsOpisUsluge;
            lhsOpisUsluge = this.getOpisUsluge();
            String rhsOpisUsluge;
            rhsOpisUsluge = that.getOpisUsluge();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "opisUsluge", lhsOpisUsluge), LocatorUtils.property(thatLocator, "opisUsluge", rhsOpisUsluge), lhsOpisUsluge, rhsOpisUsluge)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theNazivUsluge;
            theNazivUsluge = this.getNazivUsluge();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nazivUsluge", theNazivUsluge), currentHashCode, theNazivUsluge);
        }
        {
            String theOpisUsluge;
            theOpisUsluge = this.getOpisUsluge();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "opisUsluge", theOpisUsluge), currentHashCode, theOpisUsluge);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
