//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 08:04:01 PM CEST 
//


package com.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long/>
 *         &lt;element name="Naziv_Usluge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Opis_Usluge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "nazivUsluge",
    "opisUsluge"
})
@Entity
@Table(name = "dodatneusluge")
@XmlRootElement(name = "Dodatne_Usluge")
public class DodatneUsluge {

 	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY )
    @Column(name = "id_usluge", nullable = false, updatable = false)
 	@XmlElement(name = "id", required = true)
	private Long id;

    @Column(name = "nazivusluge")
    @XmlElement(name = "Naziv_Usluge", required = true)
    protected String nazivUsluge;
    @Column(name = "opisusluge")
    @XmlElement(name = "Opis_Usluge", required = true)
    protected String opisUsluge;

    /**
     * Gets the value of the idUsluge property.
     * 
     */
    public Long getId() {
		return id;
	}
 
    /**
     * Sets the value of the idUsluge property.
     * 
     */
	public void setId(Long id) {
		this.id = id;
	}


    /**
     * Gets the value of the nazivUsluge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivUsluge() {
        return nazivUsluge;
    }





	/**
     * Sets the value of the nazivUsluge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivUsluge(String value) {
        this.nazivUsluge = value;
    }

    /**
     * Gets the value of the opisUsluge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpisUsluge() {
        return opisUsluge;
    }

    /**
     * Sets the value of the opisUsluge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisUsluge(String value) {
        this.opisUsluge = value;
    }

}
