//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.01 at 05:25:45 PM CEST 
//


package com.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naziv_Kategorije" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Opis_Kategorije" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nazivKategorije",
    "opisKategorije"
})
@XmlRootElement(name = "Kategorija_Smestaja")
@Entity(name = "KategorijaSmestaja")
@Table(name = "KATEGORIJA_SMESTAJA")
@Inheritance(strategy = InheritanceType.JOINED)
public class KategorijaSmestaja
    implements Serializable, Equals, HashCode
{

    @XmlElement(name = "Naziv_Kategorije", required = true)
    protected String nazivKategorije;
    @XmlElement(name = "Opis_Kategorije", required = true)
    protected String opisKategorije;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the nazivKategorije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NAZIV_KATEGORIJE", length = 255)
    public String getNazivKategorije() {
        return nazivKategorije;
    }

    /**
     * Sets the value of the nazivKategorije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivKategorije(String value) {
        this.nazivKategorije = value;
    }

    /**
     * Gets the value of the opisKategorije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "OPIS_KATEGORIJE", length = 255)
    public String getOpisKategorije() {
        return opisKategorije;
    }

    /**
     * Sets the value of the opisKategorije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisKategorije(String value) {
        this.opisKategorije = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof KategorijaSmestaja)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final KategorijaSmestaja that = ((KategorijaSmestaja) object);
        {
            String lhsNazivKategorije;
            lhsNazivKategorije = this.getNazivKategorije();
            String rhsNazivKategorije;
            rhsNazivKategorije = that.getNazivKategorije();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nazivKategorije", lhsNazivKategorije), LocatorUtils.property(thatLocator, "nazivKategorije", rhsNazivKategorije), lhsNazivKategorije, rhsNazivKategorije)) {
                return false;
            }
        }
        {
            String lhsOpisKategorije;
            lhsOpisKategorije = this.getOpisKategorije();
            String rhsOpisKategorije;
            rhsOpisKategorije = that.getOpisKategorije();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "opisKategorije", lhsOpisKategorije), LocatorUtils.property(thatLocator, "opisKategorije", rhsOpisKategorije), lhsOpisKategorije, rhsOpisKategorije)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theNazivKategorije;
            theNazivKategorije = this.getNazivKategorije();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nazivKategorije", theNazivKategorije), currentHashCode, theNazivKategorije);
        }
        {
            String theOpisKategorije;
            theOpisKategorije = this.getOpisKategorije();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "opisKategorije", theOpisKategorije), currentHashCode, theOpisKategorije);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
