//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.01 at 05:25:45 PM CEST 
//


package com.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Ocena }
     * 
     */
    public Ocena createOcena() {
        return new Ocena();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link KategorijaSmestaja }
     * 
     */
    public KategorijaSmestaja createKategorijaSmestaja() {
        return new KategorijaSmestaja();
    }

    /**
     * Create an instance of {@link SmestajnaJedinica }
     * 
     */
    public SmestajnaJedinica createSmestajnaJedinica() {
        return new SmestajnaJedinica();
    }

    /**
     * Create an instance of {@link LokacijaTip }
     * 
     */
    public LokacijaTip createLokacijaTip() {
        return new LokacijaTip();
    }

    /**
     * Create an instance of {@link TipSmestaja }
     * 
     */
    public TipSmestaja createTipSmestaja() {
        return new TipSmestaja();
    }

    /**
     * Create an instance of {@link UslugaJedinice }
     * 
     */
    public UslugaJedinice createUslugaJedinice() {
        return new UslugaJedinice();
    }

    /**
     * Create an instance of {@link PlanCena }
     * 
     */
    public PlanCena createPlanCena() {
        return new PlanCena();
    }

    /**
     * Create an instance of {@link ZauzetostJedinice }
     * 
     */
    public ZauzetostJedinice createZauzetostJedinice() {
        return new ZauzetostJedinice();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link Admin }
     * 
     */
    public Admin createAdmin() {
        return new Admin();
    }

    /**
     * Create an instance of {@link Komentar }
     * 
     */
    public Komentar createKomentar() {
        return new Komentar();
    }

    /**
     * Create an instance of {@link DodatnaUsluga }
     * 
     */
    public DodatnaUsluga createDodatnaUsluga() {
        return new DodatnaUsluga();
    }

}
