//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.01 at 05:25:45 PM CEST 
//


package com.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Smestajna_Jedinica" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{model}User"/>
 *         &lt;element name="Ocena" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "smestajnaJedinica",
    "user",
    "ocena"
})
@XmlRootElement(name = "Ocena")
@Entity(name = "Ocena")
@Table(name = "OCENA")
@Inheritance(strategy = InheritanceType.JOINED)
public class Ocena
    implements Serializable, Equals, HashCode
{

    @XmlElement(name = "Smestajna_Jedinica")
    protected int smestajnaJedinica;
    @XmlElement(name = "User", required = true)
    protected User user;
    @XmlElement(name = "Ocena")
    protected int ocena;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the smestajnaJedinica property.
     * 
     */
    @Basic
    @Column(name = "SMESTAJNA_JEDINICA", precision = 10, scale = 0)
    public int getSmestajnaJedinica() {
        return smestajnaJedinica;
    }

    /**
     * Sets the value of the smestajnaJedinica property.
     * 
     */
    public void setSmestajnaJedinica(int value) {
        this.smestajnaJedinica = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    @ManyToOne(targetEntity = User.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "USER__OCENA_HJID")
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the ocena property.
     * 
     */
    @Basic
    @Column(name = "OCENA", precision = 10, scale = 0)
    public int getOcena() {
        return ocena;
    }

    /**
     * Sets the value of the ocena property.
     * 
     */
    public void setOcena(int value) {
        this.ocena = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Ocena)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Ocena that = ((Ocena) object);
        {
            int lhsSmestajnaJedinica;
            lhsSmestajnaJedinica = this.getSmestajnaJedinica();
            int rhsSmestajnaJedinica;
            rhsSmestajnaJedinica = that.getSmestajnaJedinica();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "smestajnaJedinica", lhsSmestajnaJedinica), LocatorUtils.property(thatLocator, "smestajnaJedinica", rhsSmestajnaJedinica), lhsSmestajnaJedinica, rhsSmestajnaJedinica)) {
                return false;
            }
        }
        {
            User lhsUser;
            lhsUser = this.getUser();
            User rhsUser;
            rhsUser = that.getUser();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "user", lhsUser), LocatorUtils.property(thatLocator, "user", rhsUser), lhsUser, rhsUser)) {
                return false;
            }
        }
        {
            int lhsOcena;
            lhsOcena = this.getOcena();
            int rhsOcena;
            rhsOcena = that.getOcena();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ocena", lhsOcena), LocatorUtils.property(thatLocator, "ocena", rhsOcena), lhsOcena, rhsOcena)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            int theSmestajnaJedinica;
            theSmestajnaJedinica = this.getSmestajnaJedinica();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "smestajnaJedinica", theSmestajnaJedinica), currentHashCode, theSmestajnaJedinica);
        }
        {
            User theUser;
            theUser = this.getUser();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "user", theUser), currentHashCode, theUser);
        }
        {
            int theOcena;
            theOcena = this.getOcena();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ocena", theOcena), currentHashCode, theOcena);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
