//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.18 at 05:10:49 PM CEST 
//


package com.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id_Ocene" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Smestajna_Jedinica" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}User"/>
 *         &lt;element name="Ocena" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idOcene",
    "smestajnaJedinica",
    "user",
    "ocena"
})
@XmlRootElement(name = "Ocena")
public class Ocena {

    @XmlElement(name = "Id_Ocene")
    protected int idOcene;
    @XmlElement(name = "Smestajna_Jedinica")
    protected int smestajnaJedinica;
    @XmlElement(name = "User", required = true)
    protected User user;
    @XmlElement(name = "Ocena")
    protected int ocena;

    /**
     * Gets the value of the idOcene property.
     * 
     */
    public int getIdOcene() {
        return idOcene;
    }

    /**
     * Sets the value of the idOcene property.
     * 
     */
    public void setIdOcene(int value) {
        this.idOcene = value;
    }

    /**
     * Gets the value of the smestajnaJedinica property.
     * 
     */
    public int getSmestajnaJedinica() {
        return smestajnaJedinica;
    }

    /**
     * Sets the value of the smestajnaJedinica property.
     * 
     */
    public void setSmestajnaJedinica(int value) {
        this.smestajnaJedinica = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the ocena property.
     * 
     */
    public int getOcena() {
        return ocena;
    }

    /**
     * Sets the value of the ocena property.
     * 
     */
    public void setOcena(int value) {
        this.ocena = value;
    }

}
