//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 08:04:01 PM CEST 
//


package com.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Plan_Cena_Tip complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Plan_Cena_Tip">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cena" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Pocetak_Vazenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Kraj_Vazenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plan_Cena_Tip", propOrder = {
    "cena",
    "pocetakVazenja",
    "krajVazenja"
})
public class PlanCenaTip {

    @XmlElement(name = "Cena")
    protected double cena;
    @XmlElement(name = "Pocetak_Vazenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pocetakVazenja;
    @XmlElement(name = "Kraj_Vazenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar krajVazenja;

    /**
     * Gets the value of the cena property.
     * 
     */
    public double getCena() {
        return cena;
    }

    /**
     * Sets the value of the cena property.
     * 
     */
    public void setCena(double value) {
        this.cena = value;
    }

    /**
     * Gets the value of the pocetakVazenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPocetakVazenja() {
        return pocetakVazenja;
    }

    /**
     * Sets the value of the pocetakVazenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPocetakVazenja(XMLGregorianCalendar value) {
        this.pocetakVazenja = value;
    }

    /**
     * Gets the value of the krajVazenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getKrajVazenja() {
        return krajVazenja;
    }

    /**
     * Sets the value of the krajVazenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKrajVazenja(XMLGregorianCalendar value) {
        this.krajVazenja = value;
    }

}
