//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.01 at 05:25:45 PM CEST 
//


package com.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naziv_Tipa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Opis_Tipa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nazivTipa",
    "opisTipa"
})
@XmlRootElement(name = "Tip_Smestaja")
@Entity(name = "TipSmestaja")
@Table(name = "TIP_SMESTAJA")
@Inheritance(strategy = InheritanceType.JOINED)
public class TipSmestaja
    implements Serializable, Equals, HashCode
{

    @XmlElement(name = "Naziv_Tipa", required = true)
    protected String nazivTipa;
    @XmlElement(name = "Opis_Tipa", required = true)
    protected String opisTipa;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the nazivTipa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NAZIV_TIPA", length = 255)
    public String getNazivTipa() {
        return nazivTipa;
    }

    /**
     * Sets the value of the nazivTipa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivTipa(String value) {
        this.nazivTipa = value;
    }

    /**
     * Gets the value of the opisTipa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "OPIS_TIPA", length = 255)
    public String getOpisTipa() {
        return opisTipa;
    }

    /**
     * Sets the value of the opisTipa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisTipa(String value) {
        this.opisTipa = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TipSmestaja)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final TipSmestaja that = ((TipSmestaja) object);
        {
            String lhsNazivTipa;
            lhsNazivTipa = this.getNazivTipa();
            String rhsNazivTipa;
            rhsNazivTipa = that.getNazivTipa();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nazivTipa", lhsNazivTipa), LocatorUtils.property(thatLocator, "nazivTipa", rhsNazivTipa), lhsNazivTipa, rhsNazivTipa)) {
                return false;
            }
        }
        {
            String lhsOpisTipa;
            lhsOpisTipa = this.getOpisTipa();
            String rhsOpisTipa;
            rhsOpisTipa = that.getOpisTipa();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "opisTipa", lhsOpisTipa), LocatorUtils.property(thatLocator, "opisTipa", rhsOpisTipa), lhsOpisTipa, rhsOpisTipa)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theNazivTipa;
            theNazivTipa = this.getNazivTipa();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nazivTipa", theNazivTipa), currentHashCode, theNazivTipa);
        }
        {
            String theOpisTipa;
            theOpisTipa = this.getOpisTipa();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "opisTipa", theOpisTipa), currentHashCode, theOpisTipa);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
