//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.01 at 05:25:45 PM CEST 
//


package com.model;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for Usluga_Jedinice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Usluga_Jedinice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Usluga" type="{model}Dodatna_Usluga"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Usluga_Jedinice", propOrder = {
    "usluga"
})
@Entity(name = "UslugaJedinice")
@Table(name = "USLUGA_JEDINICE")
@Inheritance(strategy = InheritanceType.JOINED)
public class UslugaJedinice
    implements Serializable, Equals, HashCode
{

    @XmlElement(name = "Usluga", required = true)
    protected DodatnaUsluga usluga;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the usluga property.
     * 
     * @return
     *     possible object is
     *     {@link DodatnaUsluga }
     *     
     */
    @ManyToOne(targetEntity = DodatnaUsluga.class, cascade = {
        CascadeType.MERGE
    })
    @JoinColumn(name = "USLUGA_USLUGA_JEDINICE_HJID")
    public DodatnaUsluga getUsluga() {
        return usluga;
    }

    /**
     * Sets the value of the usluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link DodatnaUsluga }
     *     
     */
    public void setUsluga(DodatnaUsluga value) {
        this.usluga = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof UslugaJedinice)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final UslugaJedinice that = ((UslugaJedinice) object);
        {
            DodatnaUsluga lhsUsluga;
            lhsUsluga = this.getUsluga();
            DodatnaUsluga rhsUsluga;
            rhsUsluga = that.getUsluga();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "usluga", lhsUsluga), LocatorUtils.property(thatLocator, "usluga", rhsUsluga), lhsUsluga, rhsUsluga)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            DodatnaUsluga theUsluga;
            theUsluga = this.getUsluga();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "usluga", theUsluga), currentHashCode, theUsluga);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
