//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.20 at 11:32:02 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "model", 
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns = {
        @XmlNs(prefix="myns", namespaceURI="model")
    }
		)

package com.soapservices;

import javax.xml.bind.annotation.XmlNs;
