
package net.codejava.ws.binary.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImageWebServiceImplService", targetNamespace = "http://impl.com/", wsdlLocation = "http://localhost:8081/codejava/fileService?wsdl")
public class ImageWebServiceImplService
    extends Service
{

    private final static URL IMAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMAGEWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName IMAGEWEBSERVICEIMPLSERVICE_QNAME = new QName("http://impl.com/", "ImageWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/codejava/fileService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        IMAGEWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ImageWebServiceImplService() {
        super(__getWsdlLocation(), IMAGEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ImageWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMAGEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ImageWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, IMAGEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ImageWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMAGEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ImageWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImageWebServiceImpl
     */
    @WebEndpoint(name = "ImageWebServiceImplPort")
    public ImageWebServiceImpl getImageWebServiceImplPort() {
        return super.getPort(new QName("http://impl.com/", "ImageWebServiceImplPort"), ImageWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImageWebServiceImpl
     */
    @WebEndpoint(name = "ImageWebServiceImplPort")
    public ImageWebServiceImpl getImageWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.com/", "ImageWebServiceImplPort"), ImageWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMAGEWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw IMAGEWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return IMAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
